[pkgs.rofi]
file="colors.rasi"
template='''
* {{
    theme-primary: {primary};
}}
'''

[pkgs.eww]
file="colors.scss"
template='''
$accent: {primary};
'''

[pkgs.dunst]
file="dunstrc"
template='''
[global]
frame_color = "{primary}"
'''

[palette]
rosewater="#F5E0DC"
flamingo="#F2CDCD"
mauve="#DDB6F2"
pink="#F5C2E7"
maroon="#E8A2AF"
red="#F28FAD"
peach="#F8BD96"
yellow="#FAE3B0"
green="#ABE9B3"
teal="#B5E8E0"
blue="#96CDFB"
sky="#89DCEB"
lavender="#C9CBFF"


